env:
  browser: true
  es6: true
  node: true
extends:
  - standard-with-typescript
  - plugin:jest/recommended
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2018
  sourceType: module
  project: 'tsconfig.json'
  createDefaultProgram: true
plugins:
  - '@typescript-eslint'
  - 'jest'
rules: {
  no-extend-native: ["error", { "exceptions": ["Date"] }],
  "@typescript-eslint/restrict-template-expressions": ["error", {
      "allowNumber": true,
      "allowBoolean": false,
      "allowNullable": true
    }]
}
